### ISSUE TITLE
Pact testing issue in Windows machine

### ISSUE THREAD

**Issue by premNtt** [pact-foundation/.github#17]
While running the pact testing in my Nextjs spa app, am facing the pact testing issue in windows machine error : pact-node@10.17.2: Pact Binary Error: ..\node_modules@pact-foundation\pact\node_modules@pact-foundation\pact-node\standalone\win32-1.88.83\pact\lib\ruby\bin.real\ruby.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

am using @pact-foundation versions are
"@pact-foundation/pact": "9.17.2",
"@pact-foundation/pact-node": "10.17.1",

and also am using Windows 10 Enterprise, 64-bit operating system, x64-based processor
Please help on this issue

**Comment by YOU54F** [comment]
@premNtt you should see the problem resolved with


```
"@pact-foundation/pact": "9.18.1", 
"@pact-foundation/pact-node": "10.18.0"
```

Note you should only need to install `@pact-foundation/pact` as `@pact-foundation/pact-node` is installed as a dependency
