### ISSUE TITLE
Update Profile README

### ISSUE THREAD

**Issue by JP-Ellis** [pact-foundation/.github#18]
## Motivation

Refresh the main Pact Foundation [profile README](https://github.com/pact-foundation/.github/tree/master/PROFILE).

## Suggested Changes

1. **Incorporate Pact Summary**

   A nice Pact summary exists for [Pact Python](https://github.com/pact-foundation/pact-python), [Pact PHP](https://github.com/pact-foundation/pact-php), [Pact JS](https://github.com/pact-foundation/pact-js), [Pact Go](https://github.com/pact-foundation/pact-go). It would be could to repeat the consistency with the front page too.

2. **Superfluous Stats**

   Some of the stats are, in my opinion, not too useful. In particular, I would suggest:

   1. Removing the "Joined GitHub", number of members and location
   2. removing most of the repository stats, only keeping the stargazers, forkers and watchers.
   3. Change the issues and PR stats to use the last 3 months only
   4. Remove 'most used languages' stats (it is dominated by HTML anyway)
   5. Remove recent activity (this can be seen from the activity sparklines next to each repo)
   6. Remove achievements (do we care that the Pact Foundation is a polyglot?)

3. Table of supported languages

   Open to feedback on this one, but I'm thinking of adding a table of language logos linking to the relevant Pact repository. This would hopefully make it easier for people to discover the Pact implementation they care about quite quickly.

**Comment by YOU54F** [comment]
> Table of supported languages

I think having a single page that lists them all, regardless of whether they live under the pact-foundation org or not

original issue where I floated the idea of a feature support overhaul 
- https://github.com/pact-foundation/docs.pact.io/issues/137

docs page to look at languages and support
- https://github.com/pact-foundation/docs.pact.io/pull/316/files#diff-c3d68d3f61bbc441e6855ac71ad271406f6a8c34f90af23710badd30a9db100e

but I think that page should live on the docs page, as it would be quite long for the profile page. 

As a user I would go to repositories and then filter on language or just search for go / php / python in the repo search

Maybe a link to a map of all the languages such as proposed in my mentioned PR might go some way of allowing people to find languages but also keeps the list in one place so there is only one place to update

also probably worth tabling for an RFC, what is the idea of a supported pact-foundation repo, and maybe how we define healthy
